---
title: "R Notebook"
output: html_notebook
---

```{r}
head(results)
```

```{r}
head(status)
```

```{r}
head(drivers)
```

```{r}
head(races)
```

```{r}
head(constructors)
```

```{r}
head(circuits)
```

```{r}
head(constructor_standings)
```

Dropping unwanted columns from results.

```{r}
results = results[-c(12:15)]
colnames(results)[7] = 'finalposition'
```

Merging status with results

```{r}
df.results.merged = merge(results, status, by = c('statusId'))
df.results.merged = df.results.merged %>% relocate(statusId, .after = last_col())
```

Merging drivers

```{r}
#pasting forename and surname in a new column 'fullname' in drivers df.
drivers$fullname = paste(drivers$forename, drivers$surname)
names(drivers$nationality) = 'driv_nationality' #renaming driver's nationality column
drivers_copy = drivers_copy[-c(3, 4, 9)]  #creating with only columns to be merged with results

df.results.merged = merge(df.results.merged, drivers_copy, by = c('driverId'))
```

Merging races

```{r}
races_copy = races[, c(1,3:6)]
df.results.merged = merge(df.results.merged, races_copy, by = c('raceId'))
```

Merging constructors

```{r}
constructors_copy = constructors[, c(1,3)]
colnames(df.results.merged)[22] = 'const_name'

df.results.merged = merge(df.results.merged, constructors_copy, by = 'constructorId')
df.results.merged = df.results.merged[,-c(20)]
```

Merging circuits

```{r}
circuits_copy = circuits[, c(1,3)]

df.results.merged = merge(df.results.merged, circuits_copy, by = c('circuitId'))
```

Merging constructor standings (importing constructor wins and points)

```{r}
const_standing_copy = constructor_standings[, c(2,3,4,7)]
colnames(const_standing_copy)[c(3:4)] = c('const_points', 'const_wins')

df.results.merged = merge(df.results.merged, const_standing_copy, by = c('raceId', 'constructorId'))
```

Merging driver standings (importing wins)

```{r}
df.results.merged = merge(df.results.merged, driver_standings[, c(2,3,7)], by = c('raceId', 'driverId'))
```

Processing some data columns.

```{r}
#casting fastestLapSpeed to numeric
df.results.merged$fastestLapSpeed = as.numeric(df.results.merged$fastestLapSpeed)

#substitute NA's in fastestSpeed with 0.
df.results.merged$fastestLapSpeed[is.na(df.results.merged$fastestLapSpeed)] <- 0

#Calculating drivers age and adding a relative column to the dataset
df.results.merged$driver_age = as.integer(format(df.results.merged$date, format="%Y"))- as.integer(format(df.results.merged$dob, format="%Y"))

#convert fastest lap time in number of milliseconds 
df.results.merged$fastestLap_ms = as.numeric(lubridate::ms(as.character(df.results.merged$fastestLapTime)))*1000
df.results.merged$fastestLap_ms[is.na(df.results.merged$fastestLap_ms)] <- 0
df.results.merged = df.results.merged[, -c(11)]  #dropping column of old fastestLapTime 
```
